### PR TITLE
Added Customizable Labels

### PR DESCRIPTION
**Pull request by BlueDev5**

### CODE REVIEW

**Comment by WooshiiDev** [comment]
I've noticed some problems with dark/light mode support and some missing default colours. 

It would be nice to have these fixed before I merge this into the branch. I've also changed the branch so that it's not going directly into master.

Some current changes required:
- [ ] Add dark/light mode support by adding default colours for both
- [ ] No default text colour for folder labels and will not appear when initially added to the folder list.
- [ ] Transparency for Gradients

If there are problems with some of these, then no worries we can still merge in and I'll apply the changes required.

**Comment by BlueDev5** [comment]
I have few questions.

> * Add dark/light mode support by adding default colours for both

Does that mean having 2 label colors and 2 selection gradients?

> * No default text colour for folder labels and will not appear when initially added to the folder list.

Does that mean having a bool for choosing weather or not they want custom label colors and also should that be global?

> * Transparency for Gradients. Cannot promise people want

I didn't quite understood what you meant with transparency for gradients. Because anything that unity's gradients support will be available in the color selection (which includes transparency).
Also in the screenshots that I sent on the issue saying I got gradients done. In that there were transparent gradients too.

**Comment by BlueDev5** [comment]
Also I'd like to get your views on the editor window I added. Which can be used to add a new folder to the settings scriptable and edit or remove existing ones just by going alt+selecting the folder.

**Comment by WooshiiDev** [comment]
Hey there Amogh, apologies for the long pause in response, other work has been busy and I've had no time to focus on personal projects like so 😓 

Ah yes I overlooked the gradient addition and forgot the alpha is on the top part of the gradient slider. That is my fault for misunderstanding .

When it comes to the light/dark mode support, I normally try to keep support for both light and dark mode by default without any work from the users. But that's not a problem as some of the logic is being changed for some things.

I'm pulling the label additions into a feature branch as there's a lot of change going on with some of the code. I have some changes of my own coming up so I need to be careful of how it is implemented. This is probably my fault from the get go but do not worry I am not rejecting this - I'm very happy to add this!

Some of the UI or logic may be modified just to support the changing codebase but that is the normal way of things in development 🙂 

The window is a great idea, and I was considering making a popup one at some point.

Also when v0.2 is released you will be mentioned in the version release as a contributor to the new feature addition.

Cheers,
Wooshii

**Pull request merged**
